
import "../globals.css"
import { Metadata } from "next"
import { Poppins } from "next/font/google"

import ThemeToggle from "@/components/ThemeToggle"
import Navbar from "@/components/layouts/admin/Navbar"
import { Button } from "@/components/ui/button"
import ThemeContextProvider from "@/lib/context/ThemeContextProvider"
import NavbarHome from "@/components/layouts/home/Navbar"

const popins = Poppins({
  weight: ["400", "500", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Restaurant Dashboard",
  icons: {
    icon: "/images/logo2.png",
  },
  description: "Generated by create next app",
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeContextProvider>
      <body className="w-full bg-light-bg dark:bg-dark-bg">
      <section className="w-full min-h-[80px] px-5 flex items-center justify-end">
        <NavbarHome/>
       </section>
       <main className="max-w-screen-2xl mx-auto">
        {children}
       </main>
      </body>
      </ThemeContextProvider>
    </html>
  )
}
