
import "../globals.css"
import { Metadata } from "next"
import { Poppins } from "next/font/google"

import ThemeContextProvider from "@/lib/context/ThemeContextProvider"
import NavbarHome from "@/components/layouts/home/Navbar"
import { CartProvider } from "@/lib/context/CartProvider"
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/toaster"

const popins = Poppins({
  weight: ["400", "500", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Restaurant Dashboard",
  icons: {
    icon: "/images/logo2.png",
  },
  description: "Generated by create next app",
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <CartProvider>
      <body className={cn(
        "w-full bg-light-bg dark:bg-dark-bg transition-colors ease-in-out duration-300",
        popins.className
      )}>
      <section className="w-full min-h-[80px] px-5 flex items-center justify-end">
        <NavbarHome/>
       </section>
       <main className="max-w-screen-2xl mx-auto px-3 py-2 md:py-12">
        {children}
       </main>
       <Toaster />
      </body>
      </CartProvider>
      </ThemeContextProvider>
    </html>
  )
}
