
import "../globals.css"
import { Metadata } from "next"
import { Poppins } from "next/font/google"
import ThemeContextProvider from "@/lib/context/ThemeContextProvider"
import NavbarHome from "@/components/layouts/home/Navbar"
import { CartProvider } from "@/lib/context/CartProvider"
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/toaster"
import { auth, signOut } from "@/auth"
import { SessionProvider } from "next-auth/react"
const popins = Poppins({
  weight: ["400", "500", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "I need 800+ toeic",
  icons: {
    icon: "/images/logo2.png",
  },
  description: "Generated by create next app",
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  return (
    <html lang="en">
      <ThemeContextProvider>
      <SessionProvider session={session}>
        <CartProvider>
      <body className={cn(
        "w-full bg-light-bg dark:bg-dark-bg transition-colors ease-in-out duration-300",
        popins.className
      )}>
        <NavbarHome/>

       <main className="w-full min-h-screen relative pt-[160px] overflow-hidden">
        {children}
       </main>
       <Toaster />
      </body>
      </CartProvider>
      </SessionProvider>
      </ThemeContextProvider>
    </html>
  )
}
